### ISSUE TITLE
[fix] stop `gss` overlap

### ISSUE THREAD

**Issue by lewisacidic** [lewisacidic/fish-git-abbr#1]
`git stash save` and `git status -s` overlap.

Propose
`git status` => `gs`
`git status -s` => `gss`
`git stash save` => `gsts`
```

**Comment by kuncevic** [comment]
I believe that could be done just by a simple PR, I can do that //cc @lewisacidic

**Comment by lewisacidic** [comment]
Ah thanks for offer @kuncevic, I already fixed :)

**Comment by kuncevic** [comment]
oh I c, cool, thank you!

**Comment by kuncevic** [comment]
However READ.me seems missing a bit `gss git status -s` => `gsts git status -s`

<img width="269" alt="image" src="https://user-images.githubusercontent.com/1283734/201477152-b4be9491-1164-40e6-a104-a217e30307e4.png">

**Comment by lewisacidic** [comment]
Thanks, done!
