### ISSUE TITLE
Does it suppose to work with the latst fish version?

### ISSUE THREAD

**Issue by kuncevic** [lewisacidic/fish-git-abbr#2]
I just installed the plugin ` fisher install lewisacidic/fish-git-abbr`

However none of the abbr's works, I am on v4.4.3.

**Comment by lewisacidic** [comment]
Hi! Project hadn't been updated in years and I guess fisher changed how plugins work (or it never worked??). I've updated it, so should now work.

**Comment by kuncevic** [comment]
I fixed the issue by simply restarting the terminal. So it works. One thing is that you might wanna change the `add` for `install` in README.md as `add` no longer a thing https://github.com/jorgebucaran/fisher/issues/660

**Comment by lewisacidic** [comment]
Right will do, thanks for the pointer!  

Don't like install/remove pairing personally... for me it should be install/uninstall or add/remove.
